version: "3"

networks:
  rails:

volumes:
  db-volume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - rails
    networks:
      - rails

  rails_db:
    image: mysql:8.0
    container_name: rails_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3360}:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-rails}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - rails

  rails:
    container_name: rails
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - rails_db
    volumes:
      - ./src:/src
    environment:
      TZ: "Asia/Tokyo"
      DB_HOST: rails_db
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-homestead}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - rails

